### ISSUE TITLE
The code has already been taken

### ISSUE THREAD

**Issue by bkrajendra** [ShawnClake/UserExtended#1]
Looks like this plugin has some issues as after installing it, it does not let you do anything with OCMS.
Can not install plugin, could not login or anything just throws error 
"The code has already been taken"

**Comment by bkrajendra** [comment]
The problem is with file seed_basic_user_groups.php
It has UserGroups which already exists in user plugin. Hence Ive modified run method to following:

```
    public function run()
    {


        UserGroup::create([
            'name' => 'Tester',
            'code' => 'tester',
            'description' => 'Access bleeding edge features'
        ]);

        UserGroup::create([
            'name' => 'Debugger',
            'code' => 'debugger',
            'description' => 'Debug text, buttons, and visuals appear on the pages'
        ]);

        UserGroup::create([
            'name' => 'Developer',
            'code' => 'developer',
            'description' => 'Access to the dev tools and options'
        ]);

        UserGroup::create([
            'name' => 'Banned',
            'code' => 'banned',
            'description' => 'Banned from viewing pages'
        ]);

    }

```

**Comment by ShawnClake** [comment]
Hi, you are completely correct. I noticed that error myself yesterday, but I didn't get a chance to look into the problem. Thank you for finding where the issues lies. I've gone ahead and updated the repo with code that shouldn't throw that error.

Waiting on October's website in order to push that update to the marketplace.

_Thanks,
Shawn_
