### ISSUE TITLE
Database Migration Fails during installation

### ISSUE THREAD

**Issue by abhi1693** [ShawnClake/UserExtended#26]
I get the following error while installing the plugin

```
"SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key (SQL: alter table `users_groups` drop primary key)" 
```

**Comment by abhi1693** [comment]
I think the issue is that when you remove the plugin it doesn't clean the all the tables properly and when you try reinstalling the plugin, this error is thrown. I had to manually remove all the columns injected by the plugin to make this work.

**Comment by ShawnClake** [comment]
Yea, I was struggling with this a few months ago and I was hoping I had fixed it. It has to do with the original tables structure having two primary keys and the DB migration scripts not playing nicely with that.

Thanks for the report, I will look into a way to solve this problem later today. I may end up just creating a separate users_groups table rather than trying to inject a column.

**Comment by ShawnClake** [comment]
Potential fix: Creating a migration which drops the the users_groups and user_groups table and rebuilds them from scratch. On artisan down, it will drop the tables again, and create them exactly how Rainlab.User creates them.

This should provide compatibility with other plugins and features which utilize existing Rainlab user_groups models as well as migrations.

Drawback:
- It will remove any existing groups relations in the application at the time of installing the plugin.

I've coded this up and pushed to the pre-release branch.

**Comment by ShawnClake** [comment]
Ran a fresh install test on this and then ran php artisan plugin:refresh on the UserExtended plugin. The solution above seems to have fixed the problem.
