### ISSUE TITLE
"Create" group button can be clicked with no input

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#69]
The "Create" button in the backend can be clicked with no information entered. Because the jQuery scripts I added do not consider the description box, the user can create a group or role with a description and no name or code.

![image](https://cloud.githubusercontent.com/assets/22599103/23620111/761afc2c-025b-11e7-8c44-9ea8ab6d87d8.png)

Solution: run the validate function initially once the partial is loaded.

**Comment by ShawnClake** [comment]
@QuinnBast 

In terms of formatting, I might suggest changing the error text to red, removing the capital on 'Name' and removing the word 'Error:'

For example it might say:
"You need to enter a name for the role" (And the text is colored burgundy redish.

When running initially on partial load, try to make it so it only disables the create button instead of also showing up error text. Lastly, be careful because when editing a role, theoretically it should already be error free as it should auto fill the form. In this case, disabling the create button wouldn't make sense.

**Comment by QuinnBast** [comment]
Backend looks good!
