### ISSUE TITLE
"Add user.." buttons always disabled

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#96]
I have 2 users not assigned to groups and 1 user I manually assigned to "Admin" group. The following screenshots show some bugs with the "Add user to..." buttons:

![image](https://cloud.githubusercontent.com/assets/22599103/23961722/727bc8e0-0971-11e7-915e-5fa2803499dd.png)

![image](https://cloud.githubusercontent.com/assets/22599103/23961777/9eabb2ae-0971-11e7-92fe-f4e0f7730693.png)

**Comment by ShawnClake** [comment]
@QuinnBast 

This is expected behavior. The 'Add Users to Group' button is currently disabled as its a place holder. That feature has not been created yet. The unassigned users are for users assigned to a group but are unassigned to a role.

To add a user into groups, currently, the only method is to go to the 'Users' tab and choose a user and tick the checkboxes for the groups they should be a part of. 

In the future, there will be a Role/Group managing API such that this can be done programmatically, as well as the 'Add Users to Groups' button will work.
